#:kivy 2.2.1

<FloatLayout>:

    #Label:
    #    text:
    #        """
    #        Work by João Folhadela* under the guidance of Dr. André M. Pereira & Dra. Ana Pires
    #        MSc in Eng. Physics
    #        *up201709374@fc.up.pt
    #        """
    #    pos_hint: {'x': -.27, 'y': 0}
    #    size_hint: 1.3, 0.09
    #    canvas.before:
    #        Color:
    #            rgba:0, 33/255, 115/255, 1
    #        Rectangle:
    #            pos: self.pos
    #            size: self.size

    Image:
        source: 'images/IFIMUP.png'
        size_hint: 0.2, 0.15
        pos_hint: {'x': 0.8, 'y': -0.025}
        canvas.before:
            Color:
                rgba:1, 1, 1, 0.5
            Rectangle:
                pos: self.pos
                size: self.size
    

    Label:
        text:'Test this E-Tattoo!'
        pos_hint: {'x': -0.35, 'y': 0.875}
        size_hint: 1, 0.09
        font_size: '44sp'
        bold: True
        color: (0,0,0,1)
        canvas.before:
            Color:
                rgba:1, 0, 0, 0.7
            Rectangle:
                pos: self.pos
                size: self.size

    Label:
        id: prediction
        text: "Model Prediction: \n      [- , - , - , - , -]"
        font_size: 50
        bold: True
        color: (1, 0, 0, 0.7)
        pos_hint: {'x': -0.23, 'y': 0.2}


    Image:
        source: 'images/background.png'
        size_hint: 0.4, 0.4
        pos_hint: {'x': 0.65, 'y': 0.5}

    Image:
        source: 'images/ai_robot.png'
        size_hint: 0.2, 0.2
        pos_hint: {'x': -0.0, 'y': 0.6}
    Image:
        id: plot
        source: 'images/plots.png'
        size_hint: 0.6, 0.8
        pos_hint: {'x': 0.01, 'y': -0.1}


    

    Label:
        id: countdown_text
        text: 
            u"""
            COUNTDOWN
            """
        pos_hint: {'x': 0.635, 'y': 0.36}
        size_hint: 0.35, 0.1
        font_size: '30sp'
        bold: True
        color: (1, 0, 0, 0.7)
        canvas.before:
            Color:
                rgba: 237/255, 125/255, 9/255, 1 #68/255, 114/255, 196/255, 1
            Line:
                width: 2.5
                rectangle: self.x,self.y /3.7 , self.width, self.height*3.7
    Label:
        id: countdown_number
        text: 
            """
            -
            """
        pos_hint: {'x': 0.635, 'y': 0.225}
        size_hint: 0.35, 0.1
        font_size: '60sp'
        bold: True
        color: (1, 0, 0, 0.7)


    Button:
        id: start_button
        text: 'START!'
        font_size: 20
        bold: True
        pos_hint: {'x': 0.732, 'y': 0.2}
        size_hint: .15, .15
        on_release: root.START(self)
        background_color: (50/255, 205/255, 50/255, 1)
        opacity: 0.8
        background_normal: ''
        background_disabled_normal: ''
        canvas.before:
            Color:
                rgba:0,0,0,1
            Rectangle:
                pos: self.pos
                size: self.size
            Line:
                width: 4
                rectangle: self.x, self.y, self.width+0.01, self.height+0.01


    Button:
        id: reset_button
        text: 'New Measurement'
        font_size: 22
        bold: True
        #disabled: True
        pos_hint: {'x': 0.507, 'y': 0.65}
        size_hint: .1, .1
        on_release: root.reset(self)
        background_color: (250/255, 140/255, 0, 1)
        opacity: 0
        background_normal: ''
        background_disabled_normal: ''
        canvas.before:
            Color:
                rgba:0,0,0,1
            Rectangle:
                pos: self.pos
                size: self.size
            Line:
                width: 4
                rectangle: self.x, self.y, self.width+0.01, self.height+0.01

    TextInput:
        id: true_pred
        text:'Please insert the \nposition you put \nyour finger on \nand press ENTER.'
        multiline: False
        on_text_validate: root.save_true_AP(self)
        pos_hint: {'center_x': 0.815, 'center_y': 0.29}
        size_hint: .2, .2
        background_color: (1, 1, 1, 1) if self.disabled == False else (1,1,1,0)
        opacity: 1
        #border: (4,4,4,4)
        on_double_tap: self.text = ''
        font_size: 40 if self.disabled == False else 0
        disabled: True
   




